const FRAME_RATE = 10
const GRID_SIZE = 120
const MAX_PLAYERS = 100
const FOOD_TYPES = ['NORMAL', 'POISON', 'SUPER', 'FRENZY']
const PORTAL_SPAWN_CHANCE = 0.0008

module.exports = {
    FRAME_RATE,
    GRID_SIZE,
    MAX_PLAYERS,
    FOOD_TYPES,
    PORTAL_SPAWN_CHANCE
}