const FRAME_RATE = 10
const GRID_SIZE = 120
const MAX_PLAYERS = 100
const FOOD_TYPES = ['NORMAL', 'POISON', 'SUPER', 'FRENZY', 'STAR', 'SPEED']
const PORTAL_SPAWN_CHANCE = 0.0008
const PORTAL_MAX_ENTRIES = 3
const PORTAL_MAX_AGE_MS = 60 * 1000
const STAR_DURATION_MS = 15000
const SPEED_DURATION_MS = 5000
const SPEED_BOOST_FACTOR = 0.8
const AI_COUNT = 10
const AI_ID_BASE = 1000

module.exports = {
    FRAME_RATE,
    GRID_SIZE,
    MAX_PLAYERS,
    FOOD_TYPES,
    PORTAL_SPAWN_CHANCE,
    PORTAL_MAX_ENTRIES,
    PORTAL_MAX_AGE_MS,
    STAR_DURATION_MS,
    SPEED_DURATION_MS,
    SPEED_BOOST_FACTOR,
    AI_COUNT,
    AI_ID_BASE
}