const FRAME_RATE = 10
const GRID_SIZE = 120
const MAX_PLAYERS = 100
const FOOD_TYPES = ['NORMAL', 'POISON', 'SUPER', 'FRENZY', 'STAR', 'SPEED']
const PORTAL_SPAWN_CHANCE = 0.0008
const STAR_DURATION_MS = 15000
const SPEED_DURATION_MS = 5000
const SPEED_BOOST_FACTOR = 0.8

module.exports = {
    FRAME_RATE,
    GRID_SIZE,
    MAX_PLAYERS,
    FOOD_TYPES,
    PORTAL_SPAWN_CHANCE,
    STAR_DURATION_MS,
    SPEED_DURATION_MS,
    SPEED_BOOST_FACTOR
}