const GRAVITY = 600
const PLAYER_RADIUS = 14
const HAND_LENGTH = 42
const GRAB_RADIUS = 38
const MAX_LINK_LENGTH = 85
const RELEASE_IMPULSE_MULTIPLIER = 1.8

const FRAME_RATE = 25
const PLAYERS_PER_GAME = 4

const WORLD_WIDTH = 800
const WORLD_HEIGHT = 400

module.exports = {
    GRAVITY,
    PLAYER_RADIUS,
    HAND_LENGTH,
    GRAB_RADIUS,
    MAX_LINK_LENGTH,
    RELEASE_IMPULSE_MULTIPLIER,
    FRAME_RATE,
    PLAYERS_PER_GAME,
    WORLD_WIDTH,
    WORLD_HEIGHT
}
