const MAP_WIDTH = 2000
const MAP_HEIGHT = 2000

const PLAYER_SPEED = 180
const PLAYER_RADIUS = 12
const MAX_HEALTH = 100

const ZONE_PHASE_DURATION_MS = 90 * 1000
const ZONE_DAMAGE_PER_TICK = 2
const ZONE_INITIAL_RADIUS = 1200
const ZONE_FINAL_RADIUS = 80
const ZONE_PHASE_COUNT = 6

const MELEE_RANGE = 50
const MELEE_ANGLE_RAD = Math.PI / 3
const MELEE_COOLDOWN_MS = 500
const MELEE_DAMAGE = 25
const RIFLE_DAMAGE = 15
const RIFLE_SPEED = 400
const PROJECTILE_RADIUS = 4
const RIFLE_RANGE = 800
const RIFLE_COOLDOWN_MS = 200

const PICKUP_RADIUS = 35
const LOOT_SPAWN_PER_POI = 2
const DROP_CRATE_INTERVAL_MS = 75 * 1000

const FRAME_RATE = 20
const BR_MAX_PLAYERS = 100
const AI_COUNT = 15
const AI_ID_BASE = 1000

module.exports = {
    MELEE_RANGE,
    MELEE_ANGLE_RAD,
    MELEE_COOLDOWN_MS,
    MELEE_DAMAGE,
    RIFLE_DAMAGE,
    RIFLE_SPEED,
    PROJECTILE_RADIUS,
    RIFLE_RANGE,
    RIFLE_COOLDOWN_MS,
    PICKUP_RADIUS,
    LOOT_SPAWN_PER_POI,
    DROP_CRATE_INTERVAL_MS,
    MAP_WIDTH,
    MAP_HEIGHT,
    PLAYER_SPEED,
    PLAYER_RADIUS,
    MAX_HEALTH,
    ZONE_PHASE_DURATION_MS,
    ZONE_DAMAGE_PER_TICK,
    ZONE_INITIAL_RADIUS,
    ZONE_FINAL_RADIUS,
    ZONE_PHASE_COUNT,
    FRAME_RATE,
    BR_MAX_PLAYERS,
    AI_COUNT,
    AI_ID_BASE
}
